import {  ThemeColorsProps } from './types';

  export const lightTheme: ThemeColorsProps = {
      noonYellow: '#feee00',
      noonYellowLightest: '#fffccf',
      background: '#F9F9F9',
      noonYellowMuted: '#c7ba00',
      golden: '#FFD700',
      noonBlue: '#3866df',
      noonBlueLight: '#edf2ff',
      noonBlack: '#404553',
      white: '#fff',
      grey1: '#7e859b',
      grey2: '#9ba0b1',
      grey3: '#dadce3',
      grey4: '#f3f4f8',
      ddd: '#ddd',
      grey5: '#eceef4',
      grey6: '#8692a5',
      grey7: '#f7f7f7',
      darkGrey: '#636363',
      greySeparator: '#edeef2',
      systemGreen: '#38ae04',
      systemGreenTint: '#dff1da',
      systemGreenTintLight: '#38ae040d',
      systemOrange: '#f3ac30',
      orangeTint: 'rgba(243, 172, 48, 0.3)',
      systemOrangeTint: '#fff8ec',
      systemRed: '#fa0000',
      systemRedAlt: '#ea2b2b',
      systemRedTint: '#fdecec',
      systemBlueTint: '#eff3fd',
      scrim: 'rgba(0, 0, 0, .4)',
      controlDisabled: '#cbcfd7',
      controlDisabledBg: '#f0f1f4',
      vipBlack: '#1c1c1b',
      black: '#000',
      vipDisable: '#eceef4',
      borderBlueLight: '#f0f2f7',
      supermallBg: '#2122b8',
      bluebonnet: '#241afc',
      americanBlue: '#454373',
      blueBell: '#9b98db',
      blueBellMuted: '#241afc0f',
      enbdBlack: '#1b1a1c',
      enbdGreen: '#c2f770',
  };

  export default lightTheme;
