const STRING = {
    didntHear: "Sorry! Didn't hear that",
    tryAgainResturantDishName: 'Try saying restaurant name or a dish',
    tapMic: 'Tap the microphone to try again',
    listening: 'Listening...',
    topRestaurants: 'Top Restaurants Offers',
    fetchingRestaurants:'Fetching Restaurants...',
    city: 'City',
    description:'Dummy Food Item desciption',
    emptyCart: 'Your cart is empty',
    total: 'Total',
    clearCart: 'Clear Cart',
    checkout: 'Checkout',
    home: 'Home',
    search: 'Search',
    cart: 'Cart',
    yourCart: 'Your Cart',
    outlet: 'Outlet',
    outletDetail: 'Outlet Detail',
    fetchingOutletDetail: 'Fetching Outlet Detail...',
    checkLater:'Try refreshing or check back later.',
    noItemFound: 'No Items Found',
    addAddress: 'Add Address',
    addCoupon: 'Add Coupon (Optional)',
    enterAddress: 'Enter Delivery Address',
    enterCoupon: 'Enter Coupon Code (Optional)',
    payNow: 'Pay Now',
    cartEmpty: 'Your cart is empty',
    orderPlaced: 'Order Confirmed!',
    orderOnTheWay: 'Your delicious food has been placed and is on the way.  🍽️',
    ramadam: 'Ramadan Kareem',
    payUsing: 'PAY USING',
    shippingAddress: 'Shipping Address',
    paymentMethod: 'Payment Method',
    itemTotal: 'Item Total',
    grandTotal: 'Grand Total',
    tax: 'Tax',
    discount: 'Discount',
    billSummary: 'Bill Summary',
    platformFee: 'Platform Fee',
    includeTax:'Incl. taxes and charges',

};

export default STRING;
